name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
    - uses: nanasess/setup-chromedriver@7cbd35794f8ab317f778c3172fb86c1e9b2853f7

    - name: Install dependencies
      run:  dart pub get

    - name: Validate formatting
      run:  dart format --output=none --set-exit-if-changed .

    - name: Analyze source code
      run:  dart analyze

    # Disabled; tracked via #75.
    # - name: Run tests
    #   run: |
    #     export DISPLAY=:99
    #     chromedriver --port=4444 --url-base=/wd/hub &
    #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    #     dart test
    #   env:
    #     CHROMEDRIVER_ARGS: '--no-sandbox --headless'
