name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
    - uses: nanasess/setup-chromedriver@2c49495f83dd47aa7cee6b3d20cd5a5a3e1e016d

    - name: Install dependencies
      run:  dart pub get

    - name: Validate formatting
      run:  dart format --output=none --set-exit-if-changed .

    - name: Analyze source code
      run:  dart analyze

    # Disabled; tracked via #75.
    # - name: Run tests
    #   run: |
    #     export DISPLAY=:99
    #     chromedriver --port=4444 --url-base=/wd/hub &
    #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    #     dart test
    #   env:
    #     CHROMEDRIVER_ARGS: '--no-sandbox --headless'
